// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeuqybgebphzvcyyiear.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFldXF5YmdlYnBoenZjeXlpZWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzgyMDgsImV4cCI6MjA3MzExNDIwOH0.mABcfuqW5hIzZ7B8__ATTf7JQ_zMzNjKLJLvzanMi3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});